# Classical Mechanics I (PHYS 311)
## Studio 13

*Name: Evan Toon*

*Date: 11-21-2025*

## Matrix Operations

In [ ]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Google how to represent matrices in numpy. If any of the following bolded terms are unfamiliar to you, google them! Wikipedia is your friend.

* Create a 3x3 matrix A.
* Demonstrate how to multiply that matrix by a scalar.
* Demonstrate multiplying A by a different 3x3 matrix. (This is not with the `*` operator!)
* Multiply A by a (3D) vector. (i.e. calculate Av)
* Calculate the **transpose** of A.
* Calculate the **trace** of A.
* Calculate the **determinant** of A.
* Calculate the **inverse** of A if it exists.
* Create a 3-vector with nonzero x,y,z components, and rotate it about the x axis by an angle $pi/2$. Look up the form of a 3D rotation matrix.
* EC(+0.5): Demonstrate a nonzero rotation of a 10-dimensional vector $\vec{v}=(x_1,x_2,...,x_10)$ in the $x_1,x_2$ plane

Google how to find the eigenvectors of matrices in numpy.

* Calculate a moment of inertia tensor for a system of two particles with equal mass (let's set it to 1). One at the origin, and the other at (1,1,0).
* Find the eigenvectors of this new moment of inertia tensor. (Comment on the resulting eigenvectors!) Notice that numpy will return normalized eigenvectors.
* EC(+0.5): Now that you have the eigenvectors, you can express your system in a coordinate system defined by these three eigenvectors. Calculate the the second particle position in this new coordinate system. (Remember that the $x^\prime$ component of a vector $\vec{v}$ will just be $\vec{v}\cdot\hat{x}^{\prime}$.) You should have new descriptions of the two particle positions in this new basis. Calculate the moment of inertia tensor in this new coordinate system and show that it's diagonal! i.e. the Eigenvectors of the matrix are the principle axes!

# Create a 3x3 matrix A

In [ ]:
import numpy as np

A = np.matrix( [[1,2,3], [4,5,6], [7,8,9]] )
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 1. Demonstrate how to multiply that matrix by a scalar.
# 2. Demonstrate multiplying A by a different 3x3 matrix. (This is not with the * operator!)
# 3. Multiply A by a (3D) vector. (i.e. calculate Av)

In [ ]:
# Demonstrate how to multiply that matrix by a scalar
scalar = A * 20
print("Scalar multiplication:\n", scalar)

# Demonstrate multiplying A by a different 3x3 matrix
B = np.matrix([[10,20,30] , [40,50,60], [70,80,90]])
matrix_multiply = np.dot(A, B)
print("Matrix multiplication:\n", matrix_multiply)

# Multiply A by a (3D) vector
C = np.matrix( [[5],[10],[15]] )
vector = np.dot(A, C)
print("Matrix/Vector multiplication:\n", vector)

Scalar multiplication:
 [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
Matrix multiplication:
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
Matrix/Vector multiplication:
 [[ 70]
 [160]
 [250]]


# 1. Calculate the transpose of A.
# 2. Calculate the trace of A.
# 3. Calculate the determinant of A.
# 4. Calculate the inverse of A if it exists

In [ ]:
# Calculate the transpose of A
tran_A = np.transpose(A)
print("Transpose of A:\n", tran_A)

# Calculate the trace of A
trace_A = np.trace(A)
print("Trace of A:\n", trace_A)

# Determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:\n", det_A)

### INVERSE OF A DOES NOT EXIST, BUT IF IT DID
### HERE IS HOW I WOULD FIND IT

# inv_A = np.linalg.inv(A)
# print("Inverse of A:\n", inv_A)


Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Trace of A:
 15
Determinant of A:
 0.0


# Create a 3-vector with nonzero x,y,z components, and rotate it about the x axis by an angle  $\pi$/2

In [ ]:
# New 3D Vector
vec = np.matrix( [[1],[2],[3]]  )

# Define Theta as pi/2
theta = np.pi / 2

# Rotate About the x axis
rot_x = np.matrix( [[1, 0, 0], [0, np.cos(theta), -np.sin(theta)], [0, np.sin(theta),  np.cos(theta)]] )
vec_rot = np.dot(rot_x, vec)

print(vec_rot)

[[ 1.]
 [-3.]
 [ 2.]]


# EC(+0.5): Demonstrate a nonzero rotation of a 10-dimensional vector $\vec{v}=(x_1,x_2,...,x_10)$ in the $x_1,x_2$ plane

In [ ]:
vec10 = np.matrix( [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]] )

# Identiry Matrix
diag_10 = np.eye(10)

# 2x2 Rotation Block
diag_10[0,0] = np.cos(theta)
diag_10[0,1] = -np.sin(theta)
diag_10[1,0] = np.sin(theta)
diag_10[1,1] = np.cos(theta)

# Convert to matrix
R = np.matrix(diag_10)

# Rotate
vec10_rot = np.dot(R, vec10)
print(vec10_rot)

[[-2.]
 [ 1.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


# 1. Calculate a moment of inertia tensor for a system of two particles with equal mass (let's set it to 1). One at the origin, and the other at (1,1,0).
# 2. Find the eigenvectors of this new moment of inertia tensor. (Comment on the resulting eigenvectors!) Notice that numpy will return normalized eigenvectors

In [ ]:
# Calculate a moment of inertia tensor for a system of two particles with equal
# mass (let's set it to 1). One at the origin, and the other at (1,1,0)

mass_1 = 1
mass_2 = 1

r1 = np.matrix( [[0],[0],[0]] )
r2 = np.matrix( [[1],[1],[0]] )

def inertia_tensor(m, r):
    x = r[0,0]
    y = r[1,0]
    z = r[2,0]
    return m * np.matrix( [[y**2 + z**2, -x*y, -x*z], [-x*y, x**2+z**2, -y*z], [-x*z, -y*z, x**2+y**2] ])

Tensor = inertia_tensor(mass_1,r1) + inertia_tensor(mass_2,r2)
print("Moment of Inertia Tensor:\n", Tensor)

# Find the eigenvectors of this new moment of inertia tensor
eigen_values, eigen_vectors = np.linalg.eig(Tensor)

print("Eigenvectors:\n", eigen_vectors)
print("Eigenvalues:\n", eigen_values)

# The eigenvectors represent the priciple axes of rotation. Once axis lies along
# the lines connecting the masses, and the others are perpindicular with the
# nonzero moments of inertia


Moment of Inertia Tensor:
 [[ 1 -1  0]
 [-1  1  0]
 [ 0  0  2]]
Eigenvectors:
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Eigenvalues:
 [2. 0. 2.]


# EC(+0.5): Now that you have the eigenvectors, you can express your system in a coordinate system defined by these three eigenvectors. Calculate the the second particle position in this new coordinate system. (Remember that the $x^\prime$ component of a vector $\vec{v}$ will just be $\vec{v}\cdot\hat{x}^{\prime}$.) You should have new descriptions of the two particle positions in this new basis. Calculate the moment of inertia tensor in this new coordinate system and show that it's diagonal! i.e. the Eigenvectors of the matrix are the principle axes!

In [ ]:
# Seperte eigenvectors
e1 = eigen_vectors[:,0]
e2 = eigen_vectors[:,1]
e3 = eigen_vectors[:,2]

def project(r, e1, e2, e3):
    # dot product w/ each eigenvector
    x_prime = float(r.T @ e1)
    y_prime = float(r.T @ e2)
    z_prime = float(r.T @ e3)
    return np.matrix([[x_prime],[y_prime],[z_prime]])

r1_new = project(r1, e1, e2, e3)
r2_new = project(r2, e1, e2, e3)

print("\nNew r1:\n", r1_new)
print("New r2:\n", r2_new)

# Inertia tensor in new coordinate system
Tensor_new = inertia_tensor(mass_1, r1_new) + inertia_tensor(mass_2, r2_new)

print("\nNew Moment of Inertia Tensor:\n", Tensor_new)



New r1:
 [[0.]
 [0.]
 [0.]]
New r2:
 [[0.        ]
 [1.41421356]
 [0.        ]]

New Moment of Inertia Tensor:
 [[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 2.]]


/tmp/ipython-input-1967704624.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x_prime = float(r.T @ e1)
/tmp/ipython-input-1967704624.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_prime = float(r.T @ e2)
/tmp/ipython-input-1967704624.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  z_prime = float(r.T @ e3)
